name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # At 03:23 on every 3rd day
    - cron: "23 3 */3 * *"
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run unit tests
        run: make test
      -
        name: Run e2e tests
        run: make e2e
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
